version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "app/package.json" }}
      - run:
          command: |
            [ ! -d "node_modules" ] && yarn install
            yarn generate
  test:
    docker:
      - image: circleci/node:14.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "app/package.json" }}
      - run:
          command: |
            [ ! -d "node_modules" ] && yarn install
            yarn test
  deploy-development:
    docker:
      - image: circleci/node:14.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "app/package.json" }}
      - run:
          command: |
            chmod +x ./app/deploy.sh
      - run:
          command: |
            echo 'export AWS_CLOUDFRONT=$DEV_CLOUDFRONT' >> $BASH_ENV
            echo 'export AWS_BUCKET_NAME=$DEV_BUCKET_NAME' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: change env and deploy
          working_directory: app
          command: |
            mv ./dotenv/.env.development ./.env
            ./deploy.sh
  deploy-production:
    docker:
      - image: circleci/node:14.15.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "app/package.json" }}
      - run:
          command: |
            chmod +x ./app/deploy.sh
      - run:
          command: |
            echo 'export AWS_CLOUDFRONT=$PROD_CLOUDFRONT' >> $BASH_ENV
            echo 'export AWS_BUCKET_NAME=$PROD_BUCKET_NAME' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: change env and deploy
          working_directory: app
          command: |
            mv ./dotenv/.env.production ./.env
            ./deploy.sh
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test
  deploy:
    jobs:
      - deploy-development:
          filters:
            branches:
              only:
                - develop
      - deploy-production:
          filters:
            branches:
              only:
                - main
